# Generated by Django 5.0 on 2024-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0003_product_delete_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_picture',
            field=models.ImageField(blank=True, null=True, upload_to='product_pictures/'),
        ),
    ]
