# Generated by Django 5.0 on 2024-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0004_product_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ratings',
            field=models.IntegerField(default=0),
        ),
    ]
